name: 'Departure & Design'
favicon: null
layout_spectrum: 0.15259
typography_spectrum: 0.37795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b0b0b'
    - '#929292'
    - '#575654'
    - '#cecece'
  brandStrength: 0.5
  lightness: 0.8433545082807541
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
