name: 'Departure & Design'
favicon: null
layout_spectrum: 0.35259
typography_spectrum: 0.37795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#717171'
    - '#c3c3c3'
    - '#8d9f00'
  brandStrength: 0.5625
  lightness: 0.3125
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
