name: 'Departure & Design'
favicon: null
layout_spectrum: 0.35259
typography_spectrum: 0.37795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b0e06'
    - '#47402c'
    - '#878167'
    - '#cfb779'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 1
purpose: []
