name: 'Departure & Design'
favicon: null
layout_spectrum: 0.07542912638746202
typography_spectrum: 0.11675
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.42579118465073407
  lightness: 0.8433545082807541
  saturation: 0.7766247256658971
  rhythmicContrast: 0.5342653342522681
purpose: []
