typography_spectrum: 0.37795
color:
  brandColors:
    - '#130e08'
    - '#5f4e2d'
    - '#9ea189'
    - '#e0e8b2'
    - '#ccc591'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.35259
analytics:
  google: null
  facebook: null
  twitter: null
name: Departure & Design
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Art & Design From Departure
description: Welcome to view of the world as art
purpose: []
