name: 'Departure & Design'
favicon: null
layout_spectrum: 0.35259
typography_spectrum: 0.37795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#8c8c8c'
    - '#d5d5d5'
    - '#56555b'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
