name: 'Departure & Design'
favicon: null
layout_spectrum: 0.35259
typography_spectrum: 0.37795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020106'
    - '#ffe391'
    - '#80704b'
    - '#55472e'
    - '#b29657'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
