name: 'Departure & Design'
favicon: null
layout_spectrum: 0.35259
typography_spectrum: 0.37795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#130e08'
    - '#5f4e2d'
    - '#9ea189'
    - '#e0e8b2'
    - '#ccc591'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
