name: 'Departure & Design'
favicon: null
layout_spectrum: 0.18408
typography_spectrum: 0.37795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d0d0d'
    - '#797c81'
    - '#c0c4cd'
    - '#8a6642'
  brandStrength: 0.1875
  lightness: 0.8433545082807541
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
